// 2026年度夏期の教科書過去問を、設問・選択肢・正答の意味を変えずに選択練習として収録します。
export const q05 = {
  number: 5,
  questionPage: 5,
  answerPage: 18,
  defaultPoints: 2,
  caution: '教科書の問題(5)に沿って、マンセル表色系の明度・色相・表記を判断する。図版の色は画面用の近似色。',
  items: [
    {
      part: 'A',
      prompt: 'マンセル表色系はアメリカ光学会によって修正された。',
      choices: [
        'マンセル表色系はアメリカ光学会によって修正された。',
        'マンセル表色系はJIS標準色票に従ってつくられた。',
        'マンセル表色系の色表示の「5R 4/14」は、「ピアールよんスラッシュじゅうよん」と読む。',
        'マンセル表色系の色相環は24色相である。',
      ],
      correctIndex: 0,
      explanation: '教科書の正答は①。マンセル表色系はアメリカ光学会によって修正された。',
    },
    {
      part: 'B',
      prompt: 'マンセル表色系の明度は、',
      choices: [
        '反射率が均等に変わっていくように設定されている。',
        'Neutralと呼ばれる。',
        '光を100%吸収する色の明度を0としている。',
        'PCCSの明度とは異なる基準でつくられている。',
      ],
      correctIndex: 2,
      explanation: '教科書の正答は③。光を100%吸収する理想的な黒の明度を0としている。',
    },
    {
      part: 'C',
      prompt: 'マンセル記号の表記として正しいもの',
      choices: ['0R 3/3', '7YR 4/4', '5Y 12/3', '2.5GB 3.5/4.1'],
      correctIndex: 1,
      explanation: '教科書の正答は②。色相・明度・彩度の表記規則に合うのは7YR 4/4である。',
    },
    {
      part: 'D',
      prompt: 'マンセル表色系の色相環で色相5Bに対向する位置にある色相は',
      choices: ['10R', '5YR', '10YR', '5Y'],
      correctIndex: 1,
      explanation: '教科書の正答は②。5Bに対向する位置は5YRである。',
    },
    {
      part: 'E',
      prompt: 'マンセル色立体において、同じ等明度面内に位置する色',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 0,
      explanation: '教科書の正答は①。5色の明度がほぼ同じで、色相・彩度が変化している。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q05-munsell.svg', alt: '2026年度夏期 問題5の配色選択肢Eと色票F' },
    },
    {
      part: 'F',
      prompt: '下に示した色のマンセル値として適切なもの',
      choices: ['5RP 8/4', '5R 6/10', '10R 4/4', '5YR 4/10'],
      correctIndex: 0,
      explanation: '教科書の正答は①。示された色票に対応するマンセル値は5RP 8/4である。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q05-munsell.svg', alt: '2026年度夏期 問題5の配色選択肢Eと色票F' },
    },
  ],
}
