// 2026年度夏期の教科書過去問を、設問・選択肢・正答の意味を変えずに4択練習として収録します。
export const q06 = {
  number: 6,
  questionPage: 6,
  answerPage: 18,
  defaultPoints: 2,
  caution: '教科書の問題(6)に沿って、図の見え方と錯視・残効の名称を対応づける。',
  items: [
    {
      part: 'A',
      prompt: '図1の文字色をどの色にしたとき、文字の色と背景色の境界線が激しくまたたくような現象が生じやすいか。',
      choices: ['色票①', '色票②', '色票③', '色票④'],
      correctIndex: 1,
      explanation: '教科書の正答は②。緑の背景に近い明度の赤を組みあわせると、境界がちらついて見えやすい。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'B',
      prompt: '図1のように文字色と背景色の境界線が激しくまたたくように見える現象はどれか。',
      choices: ['主観色', 'エーレンシュタイン効果', '補色残像', 'リープマン効果'],
      correctIndex: 3,
      explanation: '教科書の正答は④。このような境界のちらつきはリープマン効果と呼ばれる。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'C',
      prompt: '図1で文字色の色相を変更せずに、境界のまたたきを避ける方法として最も適切なものはどれか。',
      choices: ['ペールトーン', '高彩度色', '中彩度色', '背景色と同じ明度の色'],
      correctIndex: 0,
      explanation: '教科書の正答は①。文字色をペールトーンにして背景との明度差を確保すると、境界のちらつきを避けやすい。',
    },
    {
      part: 'D',
      prompt: '図2の黄色と青の図形の重なった部分をどの色にすると、奥と手前の色フィルムを重ねあわせたような印象が生じやすいか。',
      choices: ['色票①', '色票②', '色票③', '色票④'],
      correctIndex: 1,
      explanation: '教科書の正答は②。重なり部分を緑にすることで、黄色と青の透明な色面が重なったような見え方になる。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'E',
      prompt: '図2のように、色面が重なって半透明の層のように知覚される見え方はどれか。',
      choices: ['透明視', 'セパレーション', 'ドミナント効果', 'マッハバンド'],
      correctIndex: 0,
      explanation: '教科書の正答は①。このような見え方は透明視と呼ばれる。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'F',
      prompt: '図3の色の縞を交互に見た後、白黒の縦縞を観察すると、何色に色づいて見えやすいか。',
      choices: ['黄', '青緑', '赤', '黄緑'],
      correctIndex: 2,
      explanation: '教科書の正答は③。緑の縦縞への順応後、白黒の縦縞には補色方向の赤みが見えやすい。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'G',
      prompt: '同じ操作の後、白黒の横縞を観察すると、何色に色づいて見えやすいか。',
      choices: ['緑', '橙', '赤紫', '紫'],
      correctIndex: 0,
      explanation: '教科書の正答は①。赤の横縞への順応後、白黒の横縞には補色方向の緑みが見えやすい。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'H',
      prompt: '図3のように、縞の方向と色の組みあわせに依存して補色の残効が生じる現象はどれか。',
      choices: ['ネオンカラー効果', 'マッカロー効果', '色相の同化', 'ハーマングリッド'],
      correctIndex: 1,
      explanation: '教科書の正答は②。この方向選択的な色の残効はマッカロー効果と呼ばれる。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
  ],
}
