// 2026年度夏期の教科書過去問を、設問・選択肢・正答の意味を変えずに4択練習として収録します。
export const q06 = {
  number: 6,
  questionPage: 6,
  answerPage: 18,
  defaultPoints: 2,
  caution: '教科書の問題(6)に沿って、図の見え方と錯視・残効の名称を対応づける。',
  items: [
    {
      part: 'A',
      prompt: '図1の文字を［A］の色にしたところ、文字の色と背景色の境界線があいまいになり、ちらつきが生じた。この現象は［B］と呼ばれる。図1の場合、［A］の色の色相を変更せずに［B］を避けるには、たとえば、文字の色を［C］にするとよい。',
      choices: ['色票①', '色票②', '色票③', '色票④'],
      correctIndex: 1,
      explanation: '教科書の正答は②。緑の背景に近い明度の赤を組みあわせると、境界がちらついて見えやすい。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'B',
      prompt: '図1の文字を［A］の色にしたところ、文字の色と背景色の境界線があいまいになり、ちらつきが生じた。この現象は［B］と呼ばれる。図1の場合、［A］の色の色相を変更せずに［B］を避けるには、たとえば、文字の色を［C］にするとよい。',
      choices: ['主観色', 'エーレンシュタイン効果', '補色残像', 'リープマン効果'],
      correctIndex: 3,
      explanation: '教科書の正答は④。このような境界のちらつきはリープマン効果と呼ばれる。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'C',
      prompt: '図1の文字を［A］の色にしたところ、文字の色と背景色の境界線があいまいになり、ちらつきが生じた。この現象は［B］と呼ばれる。図1の場合、［A］の色の色相を変更せずに［B］を避けるには、たとえば、文字の色を［C］にするとよい。',
      choices: ['ペールトーン', '高彩度色', '中彩度色', '背景色と同じ明度の色'],
      correctIndex: 0,
      explanation: '教科書の正答は①。文字色をペールトーンにして背景との明度差を確保すると、境界のちらつきを避けやすい。',
    },
    {
      part: 'D',
      prompt: '図2の黄と青の図形の②の部分を［D］の色にすると、黄と青の色フィルムを重ねあわせたような印象が生じる。このような見え方は［E］と呼ばれる。',
      choices: ['色票①', '色票②', '色票③', '色票④'],
      correctIndex: 1,
      explanation: '教科書の正答は②。重なり部分を緑にすることで、黄色と青の透明な色面が重なったような見え方になる。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'E',
      prompt: '図2の黄と青の図形の②の部分を［D］の色にすると、黄と青の色フィルムを重ねあわせたような印象が生じる。このような見え方は［E］と呼ばれる。',
      choices: ['透明視', 'セパレーション', 'ドミナント効果', 'マッハバンド'],
      correctIndex: 0,
      explanation: '教科書の正答は①。このような見え方は透明視と呼ばれる。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'F',
      prompt: '図3の①と②を交互に10秒間ずつ、計10回程度見続けた後に、①に目を移すと、①の縦線は［F］に、横線は［G］に色づいて見える。この現象は［H］と呼ばれる。',
      choices: ['黄', '青緑', '赤', '黄緑'],
      correctIndex: 2,
      explanation: '教科書の正答は③。緑の縦縞への順応後、白黒の縦縞には補色方向の赤みが見えやすい。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'G',
      prompt: '図3の①と②を交互に10秒間ずつ、計10回程度見続けた後に、①に目を移すと、①の縦線は［F］に、横線は［G］に色づいて見える。この現象は［H］と呼ばれる。',
      choices: ['緑', '橙', '赤紫', '紫'],
      correctIndex: 0,
      explanation: '教科書の正答は①。赤の横縞への順応後、白黒の横縞には補色方向の緑みが見えやすい。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
    {
      part: 'H',
      prompt: '図3の①と②を交互に10秒間ずつ、計10回程度見続けた後に、①に目を移すと、①の縦線は［F］に、横線は［G］に色づいて見える。この現象は［H］と呼ばれる。',
      choices: ['ネオンカラー効果', 'マッカロー効果', '色相の同化', 'ハーマングリッド'],
      correctIndex: 1,
      explanation: '教科書の正答は②。この方向選択的な色の残効はマッカロー効果と呼ばれる。',
      questionType: 'visual-diagram',
      image: { src: '/color2-2026-summer-practice/q06-effects.svg', alt: '2026年度夏期 問題6の図1〜図3と色票選択肢' },
    },
  ],
}
