// 2026年度夏期の教科書過去問を、設問・選択肢・正答の意味を変えずに4択練習として収録します。
export const q07 = {
  number: 7,
  questionPage: 7,
  answerPage: 18,
  defaultPoints: 2,
  caution: '教科書の問題(7)に沿って、色相関係とトーン関係を判定する。図版の色は画面用の近似色。',
  items: [
    {
      part: 'A',
      prompt: 'トーンイントーン配色は、どのような配色か。',
      choices: ['同じ色調で全体をまとめた', 'トーンに対照性のある', '同系色相で明度差のある', '同じ色相で全体をまとめた'],
      correctIndex: 0,
      explanation: '教科書の正答は①。同じ色調（同一〜類似トーン）で全体をまとめる配色である。',
    },
    {
      part: 'B',
      prompt: 'トーンイントーン配色の例として最も適切なものはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 3,
      explanation: '教科書の正答は④。異なる色相を、近い明るさ・鮮やかさのトーンでまとめている。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q07-palettes.svg', alt: '2026年度夏期 問題7の配色選択肢 B・F・J' },
    },
    {
      part: 'C',
      prompt: 'トーンイントーン配色にすると、何を打ち出しやすい配色になるか。',
      choices: ['トーンの対照性', 'トーンがもつイメージ', '色相がもつイメージ', '色相の対照性'],
      correctIndex: 1,
      explanation: '教科書の正答は②。トーンをそろえることで、そのトーンがもつイメージを打ち出しやすい。',
    },
    {
      part: 'D',
      prompt: 'トーンイントーン配色と同じような効果の配色はどれか。',
      choices: ['コンプレックス', 'ドミナントトーン', 'バイカラー', 'ヘクサード'],
      correctIndex: 1,
      explanation: '教科書の正答は②。ドミナントトーン配色もトーンのイメージを前面に出す配色である。',
    },
    {
      part: 'E',
      prompt: 'トーナル配色は、主にどの範囲の色を組みあわせるか。',
      choices: ['高明度、中・高彩度', '低明度、中・低彩度', '中明度、中・低彩度', '高明度、中・低彩度'],
      correctIndex: 2,
      explanation: '教科書の正答は③。トーナル配色は中明度・中低彩度の色を中心に組みあわせる。',
    },
    {
      part: 'F',
      prompt: 'トーナル配色の例として最も適切なものはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 0,
      explanation: '教科書の正答は①。中明度・中低彩度の落ち着いた色調でまとめられている。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q07-palettes.svg', alt: '2026年度夏期 問題7の配色選択肢 B・F・J' },
    },
    {
      part: 'G',
      prompt: 'トーナル配色の典型として用いられるトーンはどれか。',
      choices: ['bトーン', 'dkトーン', 'ltトーン', 'dトーン'],
      correctIndex: 3,
      explanation: '教科書の正答は④。dトーンはトーナル配色の典型的なトーンである。',
    },
    {
      part: 'H',
      prompt: 'トーナル配色にすると、どのイメージの強い配色になるか。',
      choices: ['陽気な', '暗い', '落ち着いた', '澄んだ'],
      correctIndex: 2,
      explanation: '教科書の正答は③。中明度・中低彩度の色調により、落ち着いたイメージになりやすい。',
    },
    {
      part: 'I',
      prompt: 'フォカマイユ配色で組みあわせる色相・トーン関係として最も適切なものはどれか。',
      choices: ['類似色相の同一〜類似トーン', '対照色相の同一〜類似トーン', '同一色相の対照トーン', '類似色相の対照トーン'],
      correctIndex: 0,
      explanation: '教科書の正答は①。フォカマイユ配色は類似色相で、同一〜類似トーンを組みあわせる。',
    },
    {
      part: 'J',
      prompt: 'フォカマイユ配色の例として最も適切なものはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 2,
      explanation: '教科書の正答は③。類似色相で、トーン差も小さい2色の組みあわせである。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q07-palettes.svg', alt: '2026年度夏期 問題7の配色選択肢 B・F・J' },
    },
  ],
}
