// 2026年度夏期の教科書過去問を、設問・選択肢・正答の意味を変えずに4択練習として収録します。
export const q08 = {
  number: 8,
  questionPage: 8,
  answerPage: 18,
  defaultPoints: 2,
  caution: '教科書の問題(8)に沿って、図の色相関係・トーン関係と配色イメージを判断する。',
  items: [
    {
      part: 'A',
      prompt: '引き出しの色がトライアドになっているものはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 1,
      explanation: '教科書の正答は②。色相環を3等分する関係の3色で構成されている。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q08-techniques.svg', alt: '2026年度夏期 問題8の選択図A〜D' },
    },
    {
      part: 'B',
      prompt: 'トリコロール配色になっているものはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 2,
      explanation: '教科書の正答は③。明快な3色を対照的に用いたトリコロール配色である。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q08-techniques.svg', alt: '2026年度夏期 問題8の選択図A〜D' },
    },
    {
      part: 'C',
      prompt: 'カマイユ配色になっているものはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 2,
      explanation: '教科書の正答は③。色相差とトーン差がともに小さく、一見単色に近く見える配色である。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q08-techniques.svg', alt: '2026年度夏期 問題8の選択図A〜D' },
    },
    {
      part: 'D',
      prompt: '下の図のアに入ってテトラードになる色はどれか。',
      choices: ['色票①', '色票②', '色票③', '色票④'],
      correctIndex: 3,
      explanation: '教科書の正答は④。既存の3色と合わせて色相環上を4等分する関係になる。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q08-techniques.svg', alt: '2026年度夏期 問題8の選択図A〜D' },
    },
    {
      part: 'E',
      prompt: 'クラシックなイメージの配色では、',
      choices: [
        'ベースカラーに低明度で、中彩度のトーンのブラウン系を用いる。',
        'ベースカラーと類似色相のトーンをアソートカラーに用いると効果的である。',
        '暗く落ち着いた色調の中に、ホワイト系やpトーンの色をポイントとして組みあわせる。',
        'アクセントカラーにパープル系の明清色を用いると味わい深さが表現できる。',
      ],
      correctIndex: 0,
      explanation: '教科書の正答は①。クラシックでは低明度・中彩度程度のブラウン系をベースに用いる。',
    },
    {
      part: 'F',
      prompt: 'モダンなイメージの配色にしたいときには、',
      choices: [
        '無彩色にpトーンやltトーンの赤紫〜赤みの黄を中心にあわせる。',
        'ベースカラーにライトグレイを用いるのが適している。',
        'アソートカラーに中・高彩度の暖色系の色を用いるのが有効である。',
        '無彩色にブラウン系の色を中心にあわせるとイメージの表現につながる。',
      ],
      correctIndex: 1,
      explanation: '教科書の正答は②。モダンなイメージではライトグレイなどの無彩色をベースに用いる。',
    },
  ],
}
