// 2026年度夏期の出題内容を基に、転載を避けて学習用に再構成した問題です。
export const q16 = {
  number: 16,
  questionPage: null,
  answerPage: 1,
  defaultPoints: 2,
  caution: '画面色は近似色であるため、色相・明度・彩度と名称の由来を合わせて判断する。',
  items: [
    {
      part: 'A',
      prompt: 'Aの黄みの強い橙色の学習用色票に最も近いJIS慣用色名はどれか。',
      choices: ['橙金色', '黄丹', '黄葉色', '蘇芳'],
      correctIndex: 0,
      explanation: '橙金色は、金色を思わせる黄みの強い橙色である。黄丹よりも黄み寄りの見えを手掛かりにする。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票' },
    },
    {
      part: 'B',
      prompt: 'Bの深く落ち着いた緑の学習用色票に最も近いJIS慣用色名はどれか。',
      choices: ['刈安色', '鴇色', '常磐色', '海松色'],
      correctIndex: 2,
      explanation: '常磐色は常緑樹の葉を思わせる、濃く安定した緑である。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票' },
    },
    {
      part: 'C',
      prompt: 'Cの灰みを帯びた茶色の学習用色票に最も近いJIS慣用色名はどれか。',
      choices: ['海老茶', '煙覗き', '茶鼠', '鉄色'],
      correctIndex: 2,
      explanation: '茶鼠は茶色に鼠色を混ぜたような、灰みのある茶系色である。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票' },
    },
    {
      part: 'D',
      prompt: 'Dの明るく柔らかな赤みのピンクに最も近いJIS慣用色名はどれか。',
      choices: ['バーントアンバー', 'ポピーレッド', 'マルーン', 'ローズピンク'],
      correctIndex: 3,
      explanation: 'ローズピンクはバラの花を思わせる明るい赤紫寄りのピンクである。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票' },
    },
    {
      part: 'E',
      prompt: 'Eの鮮やかな黄色の学習用色票に最も近い外来色名はどれか。',
      choices: ['アンバー', 'テラコッタ', 'ジョンブリアン', 'ローシェンナ'],
      correctIndex: 2,
      explanation: 'ジョンブリアンはフランス語由来の鮮やかな黄色を表す色名である。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票' },
    },
    {
      part: 'F',
      prompt: 'Fの鮮やかで明るい青の学習用色票に最も近い外来色名はどれか。',
      choices: ['ウイスタリア', 'セルリアンブルー', 'ナイルブルー', 'ミッドナイトブルー'],
      correctIndex: 1,
      explanation: 'セルリアンブルーは空を思わせる鮮やかな青である。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票' },
    },
  ],
}
