// 2026年度夏期の教科書過去問を、色票から慣用色名を判断する形式を崩さず4択練習として収録します。
export const q16 = {
  number: 16,
  questionPage: 16,
  answerPage: 18,
  defaultPoints: 2,
  caution: '教科書の問題(16)と同じく、問題文で色の特徴を説明せず、色票そのものから慣用色名を判断する。画面色は近似色。',
  items: [
    {
      part: 'A',
      prompt: '色票Aに最も適切なJISの物体色の慣用色名はどれか。',
      choices: ['橙金色', '黄丹', '黄葉色', '蘇芳'],
      correctIndex: 0,
      explanation: '教科書の正答は①。色票Aは橙金色である。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票A〜F' },
    },
    {
      part: 'B',
      prompt: '色票Bに最も適切なJISの物体色の慣用色名はどれか。',
      choices: ['刈安色', '鴇色', '常磐色', '海松色'],
      correctIndex: 2,
      explanation: '教科書の正答は③。色票Bは常磐色である。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票A〜F' },
    },
    {
      part: 'C',
      prompt: '色票Cに最も適切なJISの物体色の慣用色名はどれか。',
      choices: ['海老茶', '煙覗き', '茶鼠', '鉄色'],
      correctIndex: 2,
      explanation: '教科書の正答は③。色票Cは茶鼠である。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票A〜F' },
    },
    {
      part: 'D',
      prompt: '色票Dに最も適切なJISの物体色の慣用色名はどれか。',
      choices: ['バーントアンバー', 'ポピーレッド', 'マルーン', 'ローズピンク'],
      correctIndex: 3,
      explanation: '教科書の正答は④。色票Dはローズピンクである。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票A〜F' },
    },
    {
      part: 'E',
      prompt: '色票Eに最も適切なJISの物体色の慣用色名はどれか。',
      choices: ['アンバー', 'テラコッタ', 'ジョンブリアン', 'ローシェンナ'],
      correctIndex: 2,
      explanation: '教科書の正答は③。色票Eはジョンブリアンである。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票A〜F' },
    },
    {
      part: 'F',
      prompt: '色票Fに最も適切なJISの物体色の慣用色名はどれか。',
      choices: ['ウイスタリア', 'セルリアンブルー', 'ナイルブルー', 'ミッドナイトブルー'],
      correctIndex: 1,
      explanation: '教科書の正答は②。色票Fはセルリアンブルーである。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q16-colors.svg', alt: '2026年度夏期 問題16の学習用近似色票A〜F' },
    },
  ],
}
