// 2026年度夏期の出題内容を基に、転載を避けて学習用に再構成した問題です。
export const q17 = {
  number: 17,
  questionPage: null,
  answerPage: 1,
  defaultPoints: 3,
  caution: '本試験は記述式。配色技法名と色相・明度関係を図から説明できるようにする。',
  items: [
    {
      part: 'A',
      prompt: '一つの色相を支配的に使い、色相のイメージで全体をまとめる配色技法はどれか。',
      choices: ['ドミナントカラー', 'ドミナントトーン', 'トーンオントーン', 'ナチュラル'],
      correctIndex: 0,
      explanation: '一つの色相を中心に全体を統一する配色はドミナントカラー配色である。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q17-poster.svg', alt: '配色技法を判断する独自の学習用ポスター' },
    },
    {
      part: 'B',
      prompt: '同一・類似色相の中で明度差をつけてまとめる配色技法はどれか。',
      choices: ['ドミナントカラー', 'トーンオントーン', 'トーンイントーン', 'ダイアード'],
      correctIndex: 1,
      explanation: '同一〜類似色相で明度やトーンに段階差をつける配色がトーンオントーンである。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q17-poster.svg', alt: '配色技法を判断する独自の学習用ポスター' },
    },
    {
      part: 'C',
      prompt: '黄色に近い色を明るく、青紫に近い色を暗くする自然な明度関係に沿った配色はどれか。',
      choices: ['コンプレックス', 'フォカマイユ', 'ナチュラル', 'セパレーション'],
      correctIndex: 2,
      explanation: '自然界で多く見られる色相と明度の関係に沿う配色をナチュラルハーモニーという。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q17-poster.svg', alt: '配色技法を判断する独自の学習用ポスター' },
    },
    {
      part: 'D',
      prompt: '自然な明度関係を逆転させるコンプレックス配色へ変更するとき、明るい側に用いる候補はどれか。',
      choices: ['① 黄', '② 緑', '③ 青緑', '④ 黄緑', '⑤ オフホワイト', '⑥ 黒', '⑦ 紫', '⑧ 紺', '⑨ 茶', '⑩ 暗い青'],
      correctIndex: 2,
      explanation: '青緑系を明るい側へ置き、自然な色相―明度関係を逆転させる。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q17-poster.svg', alt: '配色技法を判断する独自の学習用ポスター' },
    },
    {
      part: 'E',
      prompt: '背景色と図形色を残してスプリットコンプリメンタリーの3色配色にするとき、加える候補はどれか。',
      choices: ['① 黄', '② 緑', '③ 青緑', '④ 黄緑', '⑤ オフホワイト', '⑥ 黒', '⑦ 紫', '⑧ 紺', '⑨ 茶', '⑩ 暗い青'],
      correctIndex: 6,
      explanation: '補色の両隣に当たる色相関係をつくるため、紫を加える。',
      questionType: 'visual-color',
      image: { src: '/exam-papers/color2/2026-summer/q17-poster.svg', alt: '配色技法を判断する独自の学習用ポスター' },
    },
  ],
}
