// 2026年度夏期の教科書過去問を、記述式の手掛かりを保ったまま4択練習へ変換します。
export const q17 = {
  number: 17,
  questionPage: 17,
  answerPage: 18,
  defaultPoints: 3,
  caution: '本試験は記述式。教科書の文章中の条件から配色技法名と選択色を判断する。問題文で定義そのものを先に答えとして示さない。',
  items: [
    {
      part: 'A',
      prompt: '色みのイメージを前面に打ち出したかったので、図1を同系色相でまとめている。この配色技法はどれか。',
      choices: ['ドミナントカラー', 'ドミナントトーン', 'トーンオントーン', 'ナチュラル'],
      correctIndex: 0,
      explanation: '教科書の正答はドミナントカラー。同一・類似色相でまとめ、色相のイメージを前面に出す。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q17-poster.svg', alt: '2026年度夏期 問題17の図1と選択色' },
    },
    {
      part: 'B',
      prompt: '図1は別の配色技法ともいえる。そのうち、トーンが同一トーン以外になる配色技法はどれか。',
      choices: ['ドミナントカラー', 'トーンオントーン', 'トーンイントーン', 'ダイアード'],
      correctIndex: 1,
      explanation: '教科書の正答はトーンオントーン。同一〜類似色相の中で明度差・トーン差をつける。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q17-poster.svg', alt: '2026年度夏期 問題17の図1と選択色' },
    },
    {
      part: 'C',
      prompt: '図1で、青紫に近い色相の色よりも黄に近い色相の色のほうが明るい色でなければならない配色技法はどれか。',
      choices: ['コンプレックス', 'フォカマイユ', 'ナチュラル', 'セパレーション'],
      correctIndex: 2,
      explanation: '教科書の正答はナチュラル。黄に近い色を明るく、青紫に近い色を暗くする自然な明度関係を用いる。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q17-poster.svg', alt: '2026年度夏期 問題17の図1と選択色' },
    },
    {
      part: 'D',
      prompt: '図1をコンプレックス配色にするため、明るいほうの色を下の選択色のどれに変更するか。',
      choices: ['選択色①', '選択色②', '選択色③', '選択色④', '選択色⑤', '選択色⑥', '選択色⑦', '選択色⑧', '選択色⑨', '選択色⑩'],
      correctIndex: 2,
      explanation: '教科書の正答は③。自然な色相―明度関係を逆転させる色として選択色③を用いる。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q17-poster.svg', alt: '2026年度夏期 問題17の図1と選択色' },
    },
    {
      part: 'E',
      prompt: '図1の背景色と図の色の2色はそのままで、文字の色を変更してスプリットコンプリメンタリーの3色配色にするとき、下の選択色のどれを用いるか。',
      choices: ['選択色①', '選択色②', '選択色③', '選択色④', '選択色⑤', '選択色⑥', '選択色⑦', '選択色⑧', '選択色⑨', '選択色⑩'],
      correctIndex: 6,
      explanation: '教科書の正答は⑦。背景色・図の色との色相関係がスプリットコンプリメンタリーになる選択色⑦を用いる。',
      questionType: 'visual-color',
      image: { src: '/color2-2026-summer-practice/q17-poster.svg', alt: '2026年度夏期 問題17の図1と選択色' },
    },
  ],
}
