import { defineWinterGroup } from './utils.js'

export const q17 = defineWinterGroup({
  number: 17,
  defaultPoints: 3,
  caution: '問題(17)は本試験の記述式を、教科書の文章と図が与える手掛かりを増やさず4択練習へ変換。',
  items: [
    {
      part: 'A',
      prompt: '【本試験は記述式】図1はあまり見慣れないような新鮮な感じにしたかったので採用した配色で、明度差とともに色相差が必要となり、同一色相配色や無彩色を使った配色ではつくることができない。この配色技法はどれか。',
      choices: ['コンプレックス', 'ナチュラル', 'カマイユ', 'フォカマイユ'],
      correctIndex: 0,
      explanation: '教科書の正答はコンプレックス。図1は明度差と色相差をもつ関係で構成されている。',
      questionType: 'written-converted',
      points: 3,
      image: { src: '/color2-2025-winter-practice/q17.svg', alt: '2025年度冬期 問題17の図1を学習用に再構成したポスター' },
    },
    {
      part: 'B',
      prompt: '【本試験は記述式】図1は特色の組みあわせで、PCCSの色相環では6:yOと図の青系色を組みあわせた2色配色である。この配色技法はどれか。',
      choices: ['ダイアード', 'トライアド', 'テトラード', 'スプリットコンプリメンタリー'],
      correctIndex: 0,
      explanation: '教科書の正答はダイアード。図1の2色はPCCS色相環で対向する関係になる。',
      questionType: 'written-converted',
      points: 3,
      image: { src: '/color2-2025-winter-practice/q17.svg', alt: '2025年度冬期 問題17の図1を学習用に再構成したポスター' },
    },
    {
      part: 'C',
      prompt: '【本試験は記述式】図1で6:yOと組みあわせている青系色のPCCS色相記号はどれか。',
      choices: ['6:yO', '12:G', '18:B', '24:RP'],
      correctIndex: 2,
      explanation: '教科書の正答は18:B。PCCS色相環で6:yOと組みあわせる図1の青系色は18:Bである。',
      questionType: 'written-converted',
      points: 3,
      image: { src: '/color2-2025-winter-practice/q17.svg', alt: '2025年度冬期 問題17の図1を学習用に再構成したポスター' },
    },
    {
      part: 'D',
      prompt: '【本試験は記述式】図1の6:yOの色を8:Yと4:rOの2色に置き換えた3色配色は、PCCSではどの配色技法になるか。',
      choices: ['トライアド', 'テトラード', 'スプリットコンプリメンタリー', 'コンプレックス'],
      correctIndex: 2,
      explanation: '教科書の正答はスプリットコンプリメンタリー。6:yOの代わりに8:Yと4:rOを用いた3色配色である。',
      questionType: 'written-converted',
      points: 3,
      image: { src: '/color2-2025-winter-practice/q17.svg', alt: '2025年度冬期 問題17の図1を学習用に再構成したポスター' },
    },
    {
      part: 'E',
      prompt: '【本試験は記述式】図1の6:yOの色はマンセル表色系の色相記号では8YRと表示される。明度3.5、彩度6.0のこの色をマンセル値で正しく表したものはどれか。',
      choices: ['8YR 3.5/6.0', '8YR 6.0/3.5', '3.5YR 8/6.0', '8YR-3.5-6.0'],
      correctIndex: 0,
      explanation: '教科書の正答は8YR 3.5/6.0。マンセル値は色相、明度、彩度の順にH V/Cで表す。',
      questionType: 'written-converted',
      points: 3,
      image: { src: '/color2-2025-winter-practice/q17.svg', alt: '2025年度冬期 問題17の図1を学習用に再構成したポスター' },
    },
  ],
})
