import { defineSummerGroup } from './utils.js'

export const q07 = defineSummerGroup({
  number: 7,
  questionPage: 13,
  answerPage: 55,
  defaultPoints: 2,
  caution: '原本の一続きの空欄文とA〜Jの選択肢を維持する。',
  items: [
    {
      part: 'A',
      prompt: 'ビコロール配色は［A］2色配色である。ビコロール配色の典型的な例の一つとして、［B］のような配色があるが、ほかにも［C］の組みあわせや［D］配色などもその典型といえる。',
      choices: ['色相もトーンも近似した', 'コントラスト感のある明快な', '中間色だけを使った', '一見すると単色に見える'],
      correctIndex: 1,
      explanation: '原本解答表はA-②。ビコロール配色はコントラスト感のある明快な2色配色として説明されている。',
    },
    {
      part: 'B',
      prompt: 'ビコロール配色は［A］2色配色である。ビコロール配色の典型的な例の一つとして、［B］のような配色があるが、ほかにも［C］の組みあわせや［D］配色などもその典型といえる。',
      choices: [
        { text: '白と黒', colors: ['#f4f4f0', '#111111'] },
        { text: '黄橙の濃淡', colors: ['#d99a17', '#f2c52b'] },
        { text: '灰紫と黄緑', colors: ['#c6c1c9', '#9fbd44'] },
        { text: '青緑と紺', colors: ['#1681a1', '#203a67'] },
      ],
      correctIndex: 0,
      explanation: '原本解答表はB-①。原本では白と黒のような明快な2色配色が典型例として示されている。',
      questionType: 'visual-color',
    },
    {
      part: 'C',
      prompt: 'ビコロール配色は［A］2色配色である。ビコロール配色の典型的な例の一つとして、［B］のような配色があるが、ほかにも［C］の組みあわせや［D］配色などもその典型といえる。',
      choices: ['暗清色だけ', '明度差の小さい色', '中明度の低彩度色どうし', '高彩度色と無彩色'],
      correctIndex: 3,
      explanation: '原本解答表はC-④。高彩度色と無彩色の組みあわせもビコロール配色の典型として扱われている。',
    },
    {
      part: 'D',
      prompt: 'ビコロール配色は［A］2色配色である。ビコロール配色の典型的な例の一つとして、［B］のような配色があるが、ほかにも［C］の組みあわせや［D］配色などもその典型といえる。',
      choices: ['同一トーンの類似色相', '類似トーンの同一色相', '明度差のある対照トーン', '高明度色による類似トーン'],
      correctIndex: 2,
      explanation: '原本解答表はD-③。明度差のある対照トーン配色も典型として示されている。',
    },
    {
      part: 'E',
      prompt: 'ダイアードも2色配色であるが、これは［E］のような配色で、PCCSでは［F］な組みあわせた配色になる。',
      choices: [
        { text: '黄土色と黒', colors: ['#82601a', '#111111'] },
        { text: '薄灰色と紫', colors: ['#c9c8cf', '#6c55a5'] },
        { text: '黄と青紫', colors: ['#f2dd17', '#7b72bd'] },
        { text: '黄と黄緑', colors: ['#f2dd17', '#8fc74d'] },
      ],
      correctIndex: 2,
      explanation: '原本解答表はE-③。ダイアードは色相環を2等分した補色関係の2色配色である。',
      questionType: 'visual-color',
    },
    {
      part: 'F',
      prompt: 'ダイアードも2色配色であるが、これは［E］のような配色で、PCCSでは［F］な組みあわせた配色になる。',
      choices: ['有彩色と無彩色', '同一・類似トーン', '色相差が4〜8の色', '色相差が12の補色'],
      correctIndex: 3,
      explanation: '原本解答表はF-④。PCCSでは色相差12の補色関係を用いる。',
    },
    {
      part: 'G',
      prompt: 'トリコロール配色は3色配色であるが、これは［G］のような配色である。',
      choices: [
        { text: '赤紫・橙・緑', colors: ['#512034', '#873817', '#0e5f45'] },
        { text: 'ベージュ・灰・黒', colors: ['#cbbb95', '#68675e', '#252526'] },
        { text: '灰紫・灰茶・灰青', colors: ['#806f83', '#8a6f64', '#5b777b'] },
        { text: '淡黄・黄・黄緑', colors: ['#f1e5a2', '#f4df36', '#a9c651'] },
      ],
      correctIndex: 0,
      explanation: '原本解答表はG-①。原本の配色例をそのまま判定対象とする。',
      questionType: 'visual-color',
    },
    {
      part: 'H',
      prompt: 'また、色相の関係をスプリットコンプリメンタリーにしても3色配色になるが、PCCSでの配色例の一つが［H］である。',
      choices: [
        { text: '赤・黒・黄土', colors: ['#c02531', '#111111', '#9b6f18'] },
        { text: '青緑・橙・水色', colors: ['#168d88', '#df783b', '#5c98cf'] },
        { text: '青紫・黄・赤紫', colors: ['#6f60a7', '#f1df29', '#c9678d'] },
        { text: '青緑の濃淡', colors: ['#b4e0d0', '#41958c', '#20736d'] },
      ],
      correctIndex: 1,
      explanation: '原本解答表はH-②。原本の配色例をそのまま判定対象とする。',
      questionType: 'visual-color',
    },
    {
      part: 'I',
      prompt: '図1の4色配色は色相の関係が［I］となっているが、この配色に白と黒を加えた6色配色は［J］と呼ばれる。',
      choices: ['ドミナント', 'ペンタード', 'トーンオントーン', 'テトラード'],
      correctIndex: 3,
      explanation: '原本解答表はI-④。色相環を4等分する4色配色はテトラードである。',
    },
    {
      part: 'J',
      prompt: '図1の4色配色は色相の関係が［I］となっているが、この配色に白と黒を加えた6色配色は［J］と呼ばれる。',
      choices: ['グラデーション', 'カマイユ', 'ヘクサード', 'コンプレックスハーモニー'],
      correctIndex: 2,
      explanation: '原本解答表はJ-③。テトラードの4色に白と黒を加えた6色配色はヘクサードと呼ばれる。',
    },
  ],
})
