import { defineSummerGroup } from './utils.js'

export const q08 = defineSummerGroup({
  number: 8,
  questionPage: 14,
  answerPage: 56,
  defaultPoints: 2,
  caution: '教科書原本の図と選択肢を基準に収録。公開用図版は形状を簡略化しつつ、判定に必要な色相・明度・トーン関係を保持する。',
  items: [
    {
      part: 'A',
      prompt: 'ナチュラルハーモニーの配色になっているスニーカーはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 3,
      explanation: '教科書の正答は④。黄に近い色相を明るく、青紫に近い色相を暗くする自然な明度関係でまとめた配色である。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q8-a.svg', alt: '2025年度夏期 問題8A 図①〜④' },
    },
    {
      part: 'B',
      prompt: 'トーナル配色になっている靴下はどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 0,
      explanation: '教科書の正答は①。中明度・中低彩度の中間色を中心に、落ち着いたトーンでまとめている。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q8-b.svg', alt: '2025年度夏期 問題8B 図①〜④' },
    },
    {
      part: 'C',
      prompt: 'フォカマイユ配色になっているバッグはどれか。',
      choices: ['図①', '図②', '図③', '図④'],
      correctIndex: 1,
      explanation: '教科書の正答は②。同一・類似トーンの類似色相の中で、カマイユ配色よりわずかに変化をつけた配色である。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q8-c.svg', alt: '2025年度夏期 問題8C 図①〜④' },
    },
    {
      part: 'D',
      prompt: '下の図のアに入ってトーンオントーン配色になる色はどれか。',
      choices: ['色票①', '色票②', '色票③', '色票④'],
      correctIndex: 3,
      explanation: '教科書の正答は④。既存色と同系色相を保ちつつ明度差が明確になる暗い色が適する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q8-d.svg', alt: '2025年度夏期 問題8D 家具図と色票①〜④' },
    },
    {
      part: 'E',
      prompt: 'クリアなイメージの配色にする方法として最も適切なものはどれか。',
      choices: [
        '無彩色のハイコントラスト配色に高彩度の寒色を用いる。',
        'ホワイト系にグリーン系の暗清色を組み合わせる。',
        'pトーンやltトーンを中心に、ホワイト系を組み合わせる。',
        'ベースカラーにブラウン系のpトーンやltgトーンを用いる。',
      ],
      correctIndex: 2,
      explanation: '教科書の正答は③。明清色のp・ltトーンを中心に、さわやかな印象を強調するホワイト系を組み合わせる。',
    },
    {
      part: 'F',
      prompt: 'エレガントなイメージの配色にする方法として最も適切なものはどれか。',
      choices: [
        'YR系のトーンとltgトーン、中彩度の中間色を用いる。',
        'アクセントカラーとベースカラーのコントラストを強くする。',
        'pトーンやltgトーンを用い、パープル系の色相で明度差を抑える。',
        'ベースカラーにpトーンやltトーンの赤〜橙系を用いる。',
      ],
      correctIndex: 2,
      explanation: '教科書の正答は③。パープル系の類似色相にp・ltgトーンを用い、強すぎないコントラストで上品にまとめる。',
    },
  ],
})
