import { defineSummerGroup } from './utils.js'

export const q16 = defineSummerGroup({
  number: 16,
  questionPage: 22,
  answerPage: 60,
  defaultPoints: 2,
  caution: '原本の色票とJIS物体色の慣用色名の選択肢をそのまま対応させる。色票は原本レンダリング中央部から確認し、名称を一般知識で差し替えない。',
  items: [
    {
      part: 'A',
      prompt: 'Aの色について、最も適切なJISの物体色の慣用色名',
      choices: ['鴇色', '鳩色', '薄色', '鶸色'],
      correctIndex: 1,
      explanation: '原本解答表はA-②。選択肢本文も原本問題ページどおり保持する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q16-a.svg', alt: '2025年度夏期 問題16 色票A' },
    },
    {
      part: 'B',
      prompt: 'Bの色について、最も適切なJISの物体色の慣用色名',
      choices: ['黄丹', '海老茶', '黄葉色', '琥珀色'],
      correctIndex: 3,
      explanation: '原本解答表はB-④。選択肢本文も原本問題ページどおり保持する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q16-b.svg', alt: '2025年度夏期 問題16 色票B' },
    },
    {
      part: 'C',
      prompt: 'Cの色について、最も適切なJISの物体色の慣用色名',
      choices: ['新橋色', '藤色', '海松色', '緑青色'],
      correctIndex: 0,
      explanation: '原本解答表はC-①。選択肢本文も原本問題ページどおり保持する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q16-c.svg', alt: '2025年度夏期 問題16 色票C' },
    },
    {
      part: 'D',
      prompt: 'Dの色について、最も適切なJISの物体色の慣用色名',
      choices: ['ローアンバー', 'タン', 'バーガンディー', 'ポピーレッド'],
      correctIndex: 3,
      explanation: '原本解答表はD-④。選択肢本文も原本問題ページどおり保持する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q16-d.svg', alt: '2025年度夏期 問題16 色票D' },
    },
    {
      part: 'E',
      prompt: 'Eの色について、最も適切なJISの物体色の慣用色名',
      choices: ['テラコッタ', 'バーミリオン', 'バーントアンバー', 'ローシェンナ'],
      correctIndex: 2,
      explanation: '原本解答表はE-③。選択肢本文も原本問題ページどおり保持する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q16-e.svg', alt: '2025年度夏期 問題16 色票E' },
    },
    {
      part: 'F',
      prompt: 'Fの色について、最も適切なJISの物体色の慣用色名',
      choices: ['ウイスタリア', 'サックスブルー', 'スレートグレイ', 'ライラック'],
      correctIndex: 1,
      explanation: '原本解答表はF-②。選択肢本文も原本問題ページどおり保持する。',
      questionType: 'visual-color',
      image: { src: '/past-exams/color2/2025-summer/q16-f.svg', alt: '2025年度夏期 問題16 色票F' },
    },
  ],
})
